### ISSUE TITLE
No warning/error on non-existing modules

### ISSUE THREAD

**Issue by strongly-typed** [modm-io/lbuild#10]
You can add arbitrary module lines like `<module>This does not exist and is bullshit</module>` and there will be no error or warning. This is very unpleasant if modules names in modm changed and you will get no feedback from lbuild that a requested module was not found.

Accidentally reported against wrong project dergraaf/library-builder#31

**Comment by salkinium** [comment]
Uuups, that's not good. That's missing test coverage, I'll look into it.
