### ISSUE TITLE
Git repository without branch in project.xml

### ISSUE THREAD

**Issue by cajt** [modm-io/lbuild#26]
Running `lbuild init` with a project.xml containing a git repo without a defined branch silently fails to clone the repository. 
An error message or exception might be useful.

**Comment by salkinium** [comment]
The functionality is not documented on purpose, since it's not particularly robust. Not even entirely sure this should be part of lbuild at all.

cc @dergraaf

**Comment by cajt** [comment]
I'm not sure what you include in "the functionality", but please consider that managing the repo makes a huge part of the build process reproducible.

**Comment by salkinium** [comment]
Yes, sorry, that sentence reads a bit rude, I’ll talk to Fabian to figure out how we proceed, because we don’t want to build a package manager here, and this is definitely going in that direction.

**Comment by salkinium** [comment]
cc @dergraaf
