### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by colombojrj** [modm-io/lbuild#81]
Hi. This is a great and I have used it a lot at work. Thank you very much.

My question is: at github repository, lbuild does not have any version (or tag). However, PyPi tells me lbuild is in 1.21.7. I am writing a Gentoo ebuild script and it would very handy to know if lbuild has versions or not.

Sorry if this question was asked before or if it is dumb.

**Comment by rleh** [comment]
The lbuild version is (en)coded in [`lbuild/main.py:25`](https://github.com/modm-io/lbuild/blob/1b3659f32ed419474cce851356f8c0bce412e66f/lbuild/main.py#L25) and gets incremented manually with every changeset.

**Comment by colombojrj** [comment]
Thanks for the quick answer. I managed to write a simple ebuild for gentoo users. If it helps someone, here is the link: https://gitlab.com/colombojrj/gentoo-overlay/-/blob/main/dev-python/lbuild/lbuild-1.21.7.ebuild?ref_type=heads

**Comment by salkinium** [comment]
Out of curiosity, what do you use lbuild for at work?

**Comment by colombojrj** [comment]
I am just a teacher. I use modm with the students in my classes (electrical machines, power inverters, etc).
